### PR TITLE
Fixes to compile with clang-1205.0.22.9

### PR DESCRIPTION
**Pull request by jcard0na**
Fixes for the following errors and warnings when compiling on MacOS:

```
In file included from sf2filesplitter.cc:2:
./sf2.h:329:75: error: a space is required between consecutive right angle brackets (use '> >')
  std::map<uint32_t/*start*/, std::map<uint32_t/*end*/, uint32_t/*offset*/>> sampleAreas;
                                                                          ^~
                                                                          > >
In file included from sf2.cc:2:
./sf2.h:329:75: error: a space is required between consecutive right angle brackets (use '> >')
  std::map<uint32_t/*start*/, std::map<uint32_t/*end*/, uint32_t/*offset*/>> sampleAreas;
                                                                          ^~
                                                                          > >
In file included from sf2-split.cc:2:
./sf2.h:329:75: error: a space is required between consecutive right angle brackets (use '> >')
  std::map<uint32_t/*start*/, std::map<uint32_t/*end*/, uint32_t/*offset*/>> sampleAreas;
                                                                          ^~
                                                                          > >
In file included from sf2-test.cc:2:
./sf2.h:329:75: error: a space is required between consecutive right angle brackets (use '> >')
  std::map<uint32_t/*start*/, std::map<uint32_t/*end*/, uint32_t/*offset*/>> sampleAreas;
                                                                          ^~
                                                                          > >
sf2filesplitter.cc:56:5: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
    delete data;
    ^
          []
sf2filesplitter.cc:51:16: note: allocated with 'new[]' here
  char *data = new char[len];
               ^
sf2filesplitter.cc:71:49: error: a space is required between consecutive right angle brackets (use '> >')
  std::map<uint32_t, std::map<uint32_t, uint32_t>>::iterator startIter;
                                                ^~
                                                > >
sf2-split.cc:101:5: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
    delete wrFileName;
    ^
          []
sf2-split.cc:60:24: note: allocated with 'new[]' here
    char* wrFileName = new char[strlen(argv[0])+1 + 3+1 + 3+1 + SF_NAME_LEN+1 +3 +1];
                       ^
```

### CODE REVIEW

**Comment by schnitzeltony** [comment]
Thanks!
